### ISSUE TITLE
Week 1 - BaseLine Model

### ISSUE THREAD

**Issue by JWoodbury125** [JWoodbury125/machinelearningmtgecreditrisk#22]
Each group member run Final Baseline.ipynb locally.

**Comment by JWoodbury125** [comment]
Completed python pre-processing:
- [ ] Jennifer Woodbury

- [ ] Nikhil Dikshit

- [ ] Sadida Siddiqui

**Comment by NikhilDikshit** [comment]
I have completed the assigned task. 

<img width="1552" alt="screen shot 2019-02-08 at 9 54 51 pm" src="https://user-images.githubusercontent.com/16932656/52515642-74997100-2bec-11e9-9d1e-7ef1f50957ce.png">

There are 2 things in the code I want to update:
1. In[72] in the jupyter notebook should come before In[70] - because we are defining variables in line 72 which are then used in line 70.
2. In In[74] use print() to display the 'accepted/declined' output because evaluatorApplication function is just 'returning' the desired result.

Also, we can remove the unused import statements (except the pandas) for clean code.

**Comment by JWoodbury125** [comment]
Please update code as suggested Nikhil
